
name: Publish Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6

      - name: Build release distributions
        run: |
          uv build

      - name: Publish release distributions to PyPI
        run: |
          uv publish
